In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/raw_house_data - raw_house_data.csv')

In [7]:
df = df.dropna()

In [8]:
df.shape

(4370, 16)

In [9]:
df.isnull().sum()

MLS                 0
sold_price          0
zipcode             0
longitude           0
latitude            0
lot_acres           0
taxes               0
year_built          0
bedrooms            0
bathrooms           0
sqrt_ft             0
garage              0
kitchen_features    0
fireplaces          0
floor_covering      0
HOA                 0
dtype: int64

In [10]:
df['total_rooms'] = df['bathrooms']+df['bedrooms']

In [11]:
df = df.drop(['bedrooms', 'bathrooms'],axis=1)

In [12]:
df['price_per_sqrtft'] = df['sold_price']/df['sqrt_ft']
df['price_per_sqrtft'] = pd.to_numeric(df['price_per_sqrtft'], errors='coerce')

In [13]:
df["bins"] = pd.qcut(df["price_per_sqrtft"], q=20, labels=False)

In [14]:
df

MLS  sold_price  zipcode   longitude   latitude  lot_acres  \
0     21530491   5300000.0    85637 -110.378200  31.356362    2154.00   
1     21529082   4200000.0    85646 -111.045371  31.594213    1707.00   
4     21306357   3411450.0    85750 -110.813768  32.285162       3.21   
5     21528016   3250000.0    85718 -110.910593  32.339090       1.67   
6     21610478   2400000.0    85712 -110.883315  32.261069       2.10   
...        ...         ...      ...         ...        ...        ...   
4988  21814465    534000.0    85739 -110.859829  32.546570       0.29   
4989  21902512    545000.0    85745 -111.061493  32.306472       1.19   
4993  21908358    565000.0    85750 -110.820216  32.307646       0.83   
4994  21909379    535000.0    85718 -110.922291  32.317496       0.18   
4996  21908591    550000.0    85750 -110.858556  32.316373       1.42   

         taxes  year_built  sqrt_ft  garage  \
0      5272.00        1941  10500.0     0.0   
1     10422.36        1997   7300.0     0.0   
4     15393.00        1995   6396.0     3.0   
5     27802.84        1999   6842.0     3.0   
6     19038.42        2001  12025.0     4.0   
...        ...         ...      ...     ...   
4988   4184.40        2006   2681.0     3.0   
4989   6326.96        2007   3720.0     4.0   
4993   4568.71        1986   2813.0     2.0   
4994   4414.00        2002   2106.0     2.0   
4996   4822.01        1990   2318.0     3.0   

                                       kitchen_features  fireplaces  \
0               Dishwasher, Freezer, Refrigerator, Oven         6.0   
1                          Dishwasher, Garbage Disposal         5.0   
4     Dishwasher, Garbage Disposal, Refrigerator, Mi...         5.0   
5     Dishwasher, Garbage Disposal, Refrigerator, Mi...         5.0   
6                    Dishwasher, Garbage Disposal, Oven         6.0   
...                                                 ...         ...   
4988  Dishwasher, Double Sink, Electric Range, Garba...         1.0   
4989  Dishwasher, Double Sink, Garbage Disposal, Gas...         1.0   
4993  Dishwasher, Double Sink, Electric Range, Garba...         2.0   
4994  Dishwasher, Double Sink, Electric Range, Garba...         1.0   
4996  Dishwasher, Double Sink, Electric Range, Garba...         1.0   

                          floor_covering  HOA  total_rooms  price_per_sqrtft  \
0                     Mexican Tile, Wood    0         23.0        504.761905   
1                   Natural Stone, Other    0          4.0        575.342466   
4                       Carpet, Concrete   55         10.0        533.372420   
5             Natural Stone, Wood, Other  422          7.0        475.007308   
6     Carpet, Natural Stone, Wood, Other    0         17.0        199.584200   
...                                  ...  ...          ...               ...   
4988                Carpet, Ceramic Tile  180          5.0        199.179411   
4989                        Ceramic Tile   12          7.0        146.505376   
4993                Carpet, Mexican Tile    6          7.0        200.853182   
4994                        Ceramic Tile  198          5.0        254.036087   
4996                Carpet, Ceramic Tile   43          7.0        237.273512   

      bins  
0       19  
1       19  
4       19  
5       19  
6        9  
...    ...  
4988     9  
4989     1  
4993     9  
4994    16  
4996    15  

[4370 rows x 17 columns]

In [42]:
new_df=df[['longitude', 'latitude', 'bins']]

In [43]:
X_reg = new_df[['longitude', 'latitude']]

In [44]:
y_reg = new_df['bins']

In [45]:
X_reg = X_reg.to_numpy()

In [46]:
y_reg = y_reg.to_numpy()

In [20]:
ninety_pct = 0.9*new_df.shape[0]

X_train = new_df.loc[:ninety_pct-1, :]
X_test = new_df.loc[ninety_pct:, :]

X_train.shape, X_test.shape

((3457, 3), (913, 3))

In [21]:
X_train = X_train.to_numpy()

In [22]:
y_train = X_train[:,2]

In [23]:
y_train

array([19., 19., 19., ...,  0., 13., 13.])

In [24]:
X_train = X_train[:,:2]

In [25]:
X_train

array([[-110.3782  ,   31.356362],
       [-111.045371,   31.594213],
       [-110.813768,   32.285162],
       ...,
       [-110.883238,   32.323465],
       [-111.054993,   32.417093],
       [-110.868639,   32.328159]])

In [38]:
X_test_1 = [[-110.3782, 31.356362]]

In [31]:
X_test = X_test.to_numpy()

In [32]:
y_test = X_test[:,2]

In [33]:
X_test = X_test[:,:2]

In [34]:
y_test

array([ 6., 14.,  7.,  6.,  5.,  4., 12.,  5.,  3.,  1.,  1.,  2.,  8.,
        7.,  9.,  2., 18.,  7.,  5.,  6.,  6., 17.,  9., 10.,  2.,  1.,
        5., 13., 14.,  1., 11.,  5.,  1., 10.,  2.,  9.,  8., 17., 16.,
        9., 13.,  2., 11., 13.,  4.,  3.,  4.,  0., 12., 16.,  6.,  2.,
       11.,  1.,  5., 12., 12.,  3.,  2.,  0.,  7.,  3.,  9., 10.,  1.,
        7., 10.,  0.,  3., 10., 19., 11.,  2.,  9.,  8., 10.,  1., 14.,
        0.,  0.,  3.,  2.,  1.,  5.,  2.,  2., 13.,  1.,  7., 14., 12.,
        4.,  4.,  7.,  3.,  0., 11.,  6.,  9.,  0., 19.,  5.,  5.,  7.,
        1.,  4.,  7., 14., 12., 11., 12.,  0., 14.,  3.,  4., 12.,  3.,
        5.,  6., 12.,  0.,  2., 10.,  7.,  5., 10.,  0.,  1., 12.,  2.,
       11.,  8.,  5., 14.,  2., 14.,  1.,  4.,  2.,  5.,  4.,  8., 13.,
       17.,  4.,  0.,  5., 12.,  1., 12., 14.,  2., 16.,  0., 14.,  1.,
        6.,  8., 11., 10., 10., 15.,  4.,  9.,  7.,  3., 12., 11.,  6.,
        6.,  2.,  4.,  1.,  9.,  7.,  2., 10.,  5., 17., 19.,  4

In [35]:
X_test

array([[-110.988321,   32.38243 ],
       [-111.00541 ,   31.838958],
       [-110.876467,   32.305228],
       ...,
       [-110.820216,   32.307646],
       [-110.922291,   32.317496],
       [-110.858556,   32.316373]])

In [47]:
class KNNClassifier():

  def fit(self,X,y):
    self.X = X
    self.y = y.astype(int)

  def predict(self, X, K,epsilon=1e-3):
    N = len(X)
    y_hat = np.zeros(N)

    for i in range(N):
      dist2 = np.sum((self.X-X[i])**2, axis=1)
      idxt = np.argsort(dist2)[:K]
      gamma_k = 1/(np.sqrt(dist2[idxt]+epsilon))

      y_hat[i] = np.bincount(self.y[idxt], weights = gamma_k).argmax()

    return y_hat

In [48]:
knnr = KNNClassifier()
knnr.fit(X_train,y_train)

In [49]:
y_hat = knnr.predict(X_train,K=3)

In [50]:
def accuracy(y,y_hat):
  return np.mean(y==y_hat)

In [30]:
accuracy(y_train,y_hat)

0.9091698004049754

In [51]:
y_reg_hat = knnr.predict(X_reg,K=3)

In [52]:
accuracy(y_reg,y_reg_hat)

0.7356979405034325

In [36]:
y_hat_test = knnr.predict(X_test,K=3)

In [37]:
accuracy(y_test,y_hat_test)

0.07886089813800658

In [39]:
y_test_1 = knnr.predict(X_test_1,K=3)

In [40]:
y_test_1

array([19.])